### ISSUE TITLE
Create tests to check calculations

### ISSUE THREAD

**Issue by ChameleonTartu** [ChameleonTartu/NorwegianLoanCalculator#1]

**Comment by udhayacommits** [comment]
@ChameleonTartu, The pytest is a good option. It would help if the code is written so that the two python function returns values. Otherwise I will need to check on how to read stdout statements for testing purposes. Do I need to verify the output print statements?

**Comment by ChameleonTartu** [comment]
@udhayacommits Can you change function, so it will return parameters and add function for printing statements?

Ideally, it should be 2 functions:
1. For calculations only
2. For printing out the result in nice human-readable format

Having 2 functions with different params will help tremendously to test the code.

**Comment by udhayacommits** [comment]
@ChameleonTartu , I have updated tests to capture the actual print statements. But having separate functions for calculations and print is better. How do I go about that, Would you create a new issue?

**Comment by ChameleonTartu** [comment]
@udhayacommits I created separate issue #6 for function decomposition. Therefore, you can create PR for the current testing and all refactoring will remain to issue #6.

I am glad that you asked because it creates a bigger scope and now issues more fine-grained.
