### ISSUE TITLE
Change current version to accept args as command line tool

### ISSUE THREAD

**Issue by ChameleonTartu** [ChameleonTartu/NorwegianLoanCalculator#2]

**Comment by udhayacommits** [comment]
Hello @ChameleonTartu ,
I would like to take this up

**Comment by ChameleonTartu** [comment]
Hi @udhayacommits. Thank you for the contribution. It is the first time I get contribution into my repo, so I am still learning how to do it right. This issue was taken by @Ghaust. Maybe you can take issue #1?

**Comment by udhayacommits** [comment]
Hello @ChameleonTartu . Thanks for responding back. I will check the other issue although I am new to writing tests. Is there any specific tool that you want to use for writing them?

**Comment by ChameleonTartu** [comment]
@udhayacommits Feel free to choose whatever you like. I have in mind [`pytest`](https://pytest.org/en/latest/) as the simplest unit-test framework/library but any solution should work fine on the current code.
